name: exp

on: push

jobs:
  fire:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: log
        run: |
          echo $context

      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'refs/tags/v2.5.0',
              message: 'exp',
              object: 'b089400',
              type: commit,
              tagger: {
                name: 'GitHub Action',
                email: 'action@github.com'
              }
            })