name: exp

on: push

jobs:
  fire:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Create tag
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.git.createTag({
      #         owner: 'syaiful-aa',
      #         repo: 'quick_math',
      #         tag: 'v2.5.0',
      #         message: 'exp',
      #         object: context.sha,
      #         type: 'commit',
      #         tagger: {
      #           name: 'GitHub Action',
      #           email: 'action@github.com'
      #         }
      #       })

      # - name: Create Tag
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           ref: 'refs/tags/v2.5.0',
      #           sha: context.sha
      #       })

      - name: Create Tag
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/syaiful-aa/quick_math/git/tags \
          -d @- <<'EOF' 
          {
            "tag":"v2.5.1",
            "message":"initial version",
            "object":"b0894005c70be201673dd17f699fa3a5d576241c",
            "type":"commit",
            "tagger":
              {
                "name": "GitHub Action",
                "email": "action@github.com",
              }
          }
          EOF