name: fire

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tag new target
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git tag -f v3.0.10 -m 'fire'
          git push -f origin v3.0.10

